# Generated by Django 5.0.1 on 2024-02-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='N/A', max_length=100)),
                ('website', models.TextField(default='N/A')),
                ('venue_img', models.TextField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='N/A', max_length=200)),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='event date')),
                ('website', models.TextField(default='N/A')),
                ('event_img', models.TextField(default='N/A')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
            options={
                'indexes': [models.Index(fields=['event_date'], name='event_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('venue', 'event_name', 'event_date'), name='event_venue_name_date_idx'),
        ),
    ]
